### ISSUE TITLE
adding new inputs fields, date and time

### ISSUE THREAD

**Issue by Mahmoudgalalz** [formwerkjs/formwerk#83]
input fields like date and datetime-local and time
are very commonly used, and building them out of the web standards creates a lot of issues

so I think adding them would be very beneficial.

so I hope to add them to the roadmap If I have some time would be sending a PR as soon as I can

**Comment by logaretm** [comment]
Date fields are 💯 on the roadmap for sure, i'm just not sure how to abstract them away since they have a few moving parts:

- A text field containing the formatted date: Should it be intractable?
- A picker with a calendar content: How do we generate the calendar, do we do it for the user or do we assume they have their own calendar component that they may want to use.
- What kind of emitted/accepted values should these components work with? Timestamps, or date objects?

Each of these questions will have an impact on the bundle size and the overall experience, so date fields are very involved. One idea we have is with Temporals shipping in browsers soon we can use that API since it is polyfillable.

I will add more details and research on the roadmap, I'm just gathering my messy notes from everywhere to have it publishable. I will close this, since it is on the roadmap and will create an issue soon with the research and details and you can help me out there.

**Comment by Mahmoudgalalz** [comment]
For sure, will be waiting, I will be around to help
