### ISSUE TITLE
implement `submitCount` and `submitErrors`

### ISSUE THREAD

**Issue by gurgeous** [formwerkjs/formwerk#84]
Hey logaretm, thanks so much for creating veevalidate and now formwerk. Your efforts are really appreciated :)

Would you consider NOT showing validation errors on blur? Users don't like it when errors appear and disappear, because it makes the form jump around. They lose context. Especially older/slower users, or users seeing something for the first time. Showing errors on blur can be real confusing. Check out the excellent gov.uk form standards:

"When to tell the user about validation errors"
https://design-system.service.gov.uk/patterns/validation/

In my experience the pattern that works best for users:

1. Disable submit button until all required fields have values
1. Only show errors on submit (never show any errors prior to submit)
1. Display fresh errors on next submit (don't change errors while they are working)

I've built zillions of forms across many companies. I even founded a SaaS forms startup. I love forms :) Just an idea since you are still working on the library. Thanks again!

**Comment by logaretm** [comment]
Hey, thank you for the suggestions. We do not validate on blur AFAIK, but we validate whenever the value changes regardless.

One thing I learned by maintaining vee-validate is there is no one size that fits all in that area. So in Formwerk, we always validate and we always generate the error, the user decides when it should be shown. 

Most of the examples in the docs utilize `:user-invalid` and `:user-valid` selectors, which is determined by the browser and not the library. That state is satisfied in chrome by interacting with the input and then blurring it, merely focusing it and blurring it without changing the value should not trigger the selectors.

So I understand how it appears to validate on blur. Maybe there is a mistake in an example in the docs? LMK.

Having said that, I believe the experience you are describing is also desired and is not doable at the moment, and I would like to make it possible to implement.

So I'm thinking about exposing: `wasSubmitted` and `submitErrors` which would allow you to build the exact experience you are describing. Would that be suitable?

**Comment by logaretm** [comment]
> I like the idea of submitErrors and wasSubmitted. The other one I use sometimes is submitCount, a generation number of sorts that can make it easy to figure out when things change.

Yea, I think we can also expose `submitCount`. Minimal effort IMO, I may get around to doing it in the weekend. Or if you want, you could create a PR for each state.

> Another piece is the concept of required fields...

Formwerk can actually track the required fields the same way it tracks disabled fields, so this is doable as long as the required fields are marked with `required` attribute.

For schemas, this is a bit challenging because we want to do it through the standard schema spec, this is actually being discussed [here](https://github.com/standard-schema/standard-schema/issues/21), feel free to drop in your perspective.

**Comment by logaretm** [comment]
This is now in progress and is being worked on by @s8n11c, expecting some PRs soon for each piece.

**Comment by logaretm** [comment]
`v0.5.0` has been tagged with a few state additions:

- `wasSubmitted`: if the form was successfully submitted.
- `isSubmitAttempted` if the form had an attempted submit, even if it was invalid.
- `submitAttemptsCount` the number of times the form had attempts to submit.

In addition to that, all fields now expose:

- `submitErrors` Which contains the most recent submit attempt error messages.
- `submitErrorMessage` which contains the most recent submit attempt error message.

I believe by using these instead of the `errorMessage` and `errors` states, you can build the experience you desire, the docs will be updated shortly. Marking this as closed for now, LMK if we need to do more to support this use-case.

**Comment by gurgeous** [comment]
I will try it, thanks guys! I hope many will benefit, not just me :) Appreciate all your hard work on this and standard schema as well.
